apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/instance: dex
    app.kubernetes.io/name: dex
  name: dex
  namespace: proxydata-proxydata
rules:
- apiGroups:
  - dex.coreos.com
  resources:
  - authcodes
  verbs:
  - create
  - delete
  - deletecollection
  - patch
  - update
- apiGroups:
  - dex.coreos.com
  resources:
  - authrequests
  verbs:
  - create
  - delete
  - deletecollection
  - patch
  - update
- apiGroups:
  - dex.coreos.com
  resources:
  - connectors
  verbs:
  - create
  - delete
  - deletecollection
  - patch
  - update
- apiGroups:
  - dex.coreos.com
  resources:
  - oauth2clients
  verbs:
  - create
  - delete
  - deletecollection
  - patch
  - update
- apiGroups:
  - dex.coreos.com
  resources:
  - offlinesessionses
  verbs:
  - create
  - delete
  - deletecollection
  - patch
  - update
- apiGroups:
  - dex.coreos.com
  resources:
  - passwords
  verbs:
  - create
  - delete
  - deletecollection
  - patch
  - update
- apiGroups:
  - dex.coreos.com
  resources:
  - refreshtokens
  verbs:
  - create
  - delete
  - deletecollection
  - patch
  - update
- apiGroups:
  - dex.coreos.com
  resources:
  - signingkeies
  verbs:
  - create
  - delete
  - deletecollection
  - patch
  - update
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: dex
    app.kubernetes.io/name: dex
  name: dex
  namespace: proxydata-proxydata
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dex
subjects:
  - kind: ServiceAccount
    name: dex
    namespace: proxydata-proxydata