---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-nifi-konpyutaika-com-v1alpha1-nificluster
  failurePolicy: Fail
  name: vnificluster.kb.io
  rules:
  - apiGroups:
    - nifi.konpyutaika.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - nificlusters
  sideEffects: None
