# permissions for end users to edit nifinodegroupautoscalers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nifinodegroupautoscaler-editor-role
rules:
- apiGroups:
  - nifi.konpyutaika.com
  resources:
  - nifinodegroupautoscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nifi.konpyutaika.com
  resources:
  - nifinodegroupautoscalers/status
  verbs:
  - get
