# permissions for end users to edit nifiusergroups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nifiusergroup-editor-role
rules:
- apiGroups:
  - nifi.konpyutaika.com
  resources:
  - nifiusergroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nifi.konpyutaika.com
  resources:
  - nifiusergroups/status
  verbs:
  - get
