# permissions for end users to edit nifidatafloworganizers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: nifidatafloworganizer-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: nifikop
    app.kubernetes.io/part-of: nifikop
    app.kubernetes.io/managed-by: kustomize
  name: nifidatafloworganizer-editor-role
rules:
- apiGroups:
  - nifi.konpyutaika.com
  resources:
  - nifidatafloworganizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nifi.konpyutaika.com
  resources:
  - nifidatafloworganizers/status
  verbs:
  - get
