# permissions for end users to edit nificonnections.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nificonnection-editor-role
rules:
- apiGroups:
  - nifi.konpyutaika.com
  resources:
  - nificonnections
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nifi.konpyutaika.com
  resources:
  - nificonnections/status
  verbs:
  - get
