# permissions for end users to view nificonnections.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nificonnection-viewer-role
rules:
- apiGroups:
  - nifi.konpyutaika.com
  resources:
  - nificonnections
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nifi.konpyutaika.com
  resources:
  - nificonnections/status
  verbs:
  - get
