# permissions for end users to view nifinodegroupautoscalers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nifinodegroupautoscaler-viewer-role
rules:
- apiGroups:
  - nifi.konpyutaika.com
  resources:
  - nifinodegroupautoscalers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nifi.konpyutaika.com
  resources:
  - nifinodegroupautoscalers/status
  verbs:
  - get
