# permissions for end users to view nifiregistryclients.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nifiregistryclient-viewer-role
rules:
- apiGroups:
  - nifi.konpyutaika.com
  resources:
  - nifiregistryclients
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nifi.konpyutaika.com
  resources:
  - nifiregistryclients/status
  verbs:
  - get
