---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: nifi-intra-nodes
spec:
  podSelector: &labels_selector
    matchLabels:
      app: nifi
  ingress:
    - from:
        - podSelector: *labels_selector
      ports: &intranodes_ports
        - port: 6007
          protocol: TCP
        - port: 8443
          protocol: TCP
    - from:
        - podSelector:
            matchLabels:
              operator: "nifi"
      ports:
        - port: 8443
          protocol: TCP
  egress:
    - to:
        - podSelector: *labels_selector
      ports: *intranodes_ports
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/instance: zookeeper
              app.kubernetes.io/name: zookeeper
      ports:
        - port: 2181
          protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: nifi-to-dex
spec:
  podSelector:
    matchLabels:
      app: nifi
  egress:
    - ports:
        - port: 6080
          protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: traefik-to-nifi
spec:
  podSelector:
    matchLabels:
      app: nifi
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: "traefik"
      ports:
        - port: 8443
          protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: nifikop-to-nifi
spec:
  podSelector:
    matchLabels:
      operator: nifi
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: "nifi"
      ports:
        - port: 8443
          protocol: TCP
---
#apiVersion: crd.projectcalico.org/v1
#kind: NetworkPolicy
#metadata:
#  name: nifi-to-dex
#spec:
#  selector: app == 'nifi'
#  types:
#    - Egress
#  egress:
#    - action: Allow
#      protocol: TCP
#      source:
#        selector: app == 'nifi'
#      destination:
#        ports: ["6080"]
#---
#---
#apiVersion: networking.k8s.io/v1
#kind: NetworkPolicy
#metadata:
#  name: allow-all-nifi
#spec:
#  podSelector:
#    matchLabels: &labels_selector
#      app: nifi
#  ingress:
#    - {}
#  egress:
#    - {}
#---
#apiVersion: networking.k8s.io/v1
#kind: NetworkPolicy
#metadata:
#  name: allow-all-nifikop
#spec:
#  podSelector:
#    matchLabels: &labels_selector
#      app: nifikop
#  ingress:
#    - {}
#  egress:
#    - {}
#---
# apiVersion: crd.projectcalico.org/v1
#  kind: NetworkPolicy
#  metadata:
#    name: allow-icmp
#  spec:
#    selector: app == 'nifi'
#    ingress:
#      - action: Allow
#        protocol: ICMP
#        source:
#          selector: app == 'nifi'