## Append samples you want in your CSV to this file as resources ##
resources:
- nifi_v1_nificluster.yaml
- nifi_v1_nifiusergroup.yaml
- nifi_v1_nifidataflow.yaml
- nifi_v1_nifiparametercontext.yaml
- nifi_v1_nifinodegroupautoscaler.yaml
- nifi_v1alpha1_nifidatafloworganizer.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
