kind: Secret
metadata:
  name: raw
  namespace: nifikop
apiVersion: v1
data:
  nifi.properties: |
    nifi.security.user.oidc.client.id=yourOIDCClientId
    nifi.security.user.oidc.client.secret=yourOIDCClientSecret