{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "nifikop.name" . }}-metrics
  namespace: {{ $.Release.Namespace }}
  labels:
    component: app
    app: {{ template "nifikop.name" . }}-metrics
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    {{ if .Values.commonLabels }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end}}
    {{- end}}
  {{ if .Values.commonAnnotations }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end}}
  {{- end}}
spec:
  selector:
    app: {{ template "nifikop.name" . }}
  ports:
  - name: metrics
    port: {{ .Values.metrics.port }}
    protocol: TCP
{{- end }}