# This is copied from config/webhook & then templated
apiVersion: v1
kind: Service
metadata:
  name: {{ template "nifikop.name" . }}-webhook-service
  namespace: {{ $.Release.Namespace }}
  labels:
    component: app
    app: {{ template "nifikop.name" . }}-webhook-service
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9443
  selector:
    control-plane: nifikop